name: project-${ENVIRONMENT}

services:
  nats-server:
    image: nats:latest

  auth-ms:
    build:
      context: ./ms-auth
      dockerfile: Dockerfile.${ENVIRONMENT}
    image: ${DOCKER_REPOSITORY}/${ENVIRONMENT}-ms-auth
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    
  ms-gateway:
    build:
      context: ./ms-gateway
      dockerfile: Dockerfile.${ENVIRONMENT}
    image: ${DOCKER_REPOSITORY}/${ENVIRONMENT}-ms-gateway
    ports:
      - ${MS_GATEWAY_PORT}:${MS_GATEWAY_PORT}
    environment:
      - PORT=${MS_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  products-ms:
    build:
      context: ./ms-products
      dockerfile: Dockerfile.${ENVIRONMENT}
    image: ${DOCKER_REPOSITORY}/${ENVIRONMENT}-ms-products
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db
  
  orders-ms:
    build: 
      context: ./ms-orders
      dockerfile: Dockerfile.${ENVIRONMENT}
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: ${DOCKER_REPOSITORY}/${ENVIRONMENT}-ms-orders
    environment:
      - PORT=3000
      - DATABASE_URL=${ORDERS_DATABASE_URL}
      - NATS_SERVERS=nats://nats-server:4222

  # payments-ms:
  #   build:
  #     context: ./ms-payments
  #     dockerfile: dockerfile.${ENVIRONMENT}
  #   image: ${DOCKER_REPOSITORY}/${ENVIRONMENT}-ms-payments
  #   ports:
  #     - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
  #   environment:
  #     - PORT=${PAYMENTS_MS_PORT}
  #     - NATS_SERVERS=nats://nats-server:4222
  #     - STRIPE_SECRET=${STRIPE_SECRET}
  #     - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
  #     - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
  #     - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      